src/core/urls.py
from django.urls import path
from .views import (
    home, add_to_cart, remove_from_cart, decrease_quantity, increase_quantity, mice_view, keyboard_view, components_view, laptops_view, audio_view, streaming_view,
    chairs_view, console_view, new_items_view, last_chance_view, exclusives_view,
    ItemDetailView, ProductAdded, CartView, CheckoutView, PaymentView, RequestRefundView, OrdersView)
app_name = 'core'



urlpatterns = [

    path('', home, name="home"),

    path('checkout/', CheckoutView.as_view(), name='checkout'),

    path('product/<slug:slug>/', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('product-added/<slug>/', ProductAdded.as_view(), name='product-added'),
    path('decrease-quantity/<slug>/', decrease_quantity, name='decrease-quantity'),
    path('increase-quantity/<slug>/', increase_quantity, name='increase-quantity'),
    path('cart/', CartView.as_view(), name='cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('orders/', OrdersView.as_view(), name='orders'),



    # Label 
    path('gaming-mice/', mice_view, name='gaming-mice'),
    path('gaming-keyboards/', keyboard_view, name='gaming-keyboards'),
    path('components/', components_view, name='components'),
    path('gaming-laptops/', laptops_view, name='gaming-laptops'),
    path('gaming-audio/', audio_view, name='gaming-audio'),
    path('gaming-chairs/', chairs_view, name='gaming-chairs'),
    path('streaming/', streaming_view, name='streaming'),
    path('console-gaming/', console_view, name='console-gaming'),

    path('new/', new_items_view, name='new'),
    path('last-chance/', last_chance_view, name='last-chance'),
    path('exclusives/', exclusives_view, name='exclusives'),
]



src/eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),

]





urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/core/models.py
import os
import decimal
from distutils.sysconfig import get_makefile_filename
import random
import uuid
from .utils import unique_slug_generator


from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField

from .utils import round_decimals_down

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{0}/{1}".format(new_filename, final_filename)

CATEGORY_CHOICES = (
    ('LAPTOPS', 'Laptops'),
    ('COMPONENTS', 'Components'),
    ('MICE', 'Mice'),
    ('KEYBOARDS', 'Keyboards'),
    ('AUDIO', 'Audio'),
    ('STREAMING', 'Streaming'),
    ('CHAIRS', 'Chairs'),
    ('CONSOLE', 'Console'),
)


LABEL_CHOICES = (
    ('D', 'discount'),
    ('E', 'exclusive'),
    ('N', 'new'),
)

ORDER_STATUS_CHOICES = (
    ('P', 'Pending'),
    ('APAY', 'Awaiting Payment'),
    ('AF', 'Awaiting Fulfillment'),
    ('AS', 'Awaiting Shipment'),
    ('APU', 'Awaiting Pickup'),
    ('PS', 'Partially Shipped'),
    ('C', 'Completed'),
    ('S', 'Shipped'),
    ('CANC', 'Cancelled'),
    ('D', 'Declined'),
    ('R', 'Refunded'),
    ('PR', 'Partially Refunded')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)




class Item(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    discount_percent = models.FloatField(default=0 , null=True, blank=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10, blank=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True, null=True)
    image = models.ImageField(upload_to=upload_image_path, default='thumbnail.png')
    detail_image = models.ImageField(upload_to=upload_image_path, default='thumbnail.png')
    summary = models.CharField(max_length=255, blank=False)
    posted = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=1000, blank=True)
    slug = models.SlugField(blank=True)

    
    def discount(self):
        if self.discount_percent > 0:
            discount_price = self.price - self.price * decimal.Decimal(self.discount_percent) / 100
            return round_decimals_down(discount_price, 2)

    def discount_badge(sender, instance, *args, **kwargs):
        if instance.discount_percent > 0:
            instance.label = 'D'
        else:
            instance.label = None

    def item_pre_save_receiver(sender, instance, *args, **kwargs):
        if not instance.slug:
            instance.slug = unique_slug_generator(instance)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product-detail", kwargs={
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    def description_list(self):
        return self.description.split('\n')

    class Meta:
        ordering = ('-posted',)

pre_save.connect(Item.item_pre_save_receiver, sender=Item)
post_save.connect(Item.discount_badge, sender=Item)

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='item')
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def price_with_out_discount(self):
        return self.item.price *  self.quantity

    def get_total_item_price(self):
        if self.item.discount_percent > 0:
            new_price = self.item.price - self.item.price * decimal.Decimal(self.item.discount_percent) / 100
        else:
            new_price = self.item.price
        total = new_price * self.quantity
        return round_decimals_down(total)




class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    created = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()    
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address', on_delete=models.SET_NULL, blank=True, null=True, related_name='billing_address')
    shipping_address = models.ForeignKey('Address', on_delete=models.SET_NULL, blank=True, null=True, related_name='shipping_address')
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.CASCADE, null=True, blank=True)
    ref_code = models.UUIDField(default=uuid.uuid4, unique=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, max_length=4, default="P")

    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username


    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return round_decimals_down(total, 2)


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=True)
    zip = models.CharField(max_length=100)

    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField(max_length=255)


    def __str__(self):
        return f"{self.pk}"

src/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8725b2e310.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
    {% include 'navbar.html' %}
    
    {% block content %}

    {% endblock %}

    {% block extra_body %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% block extra_scripts %}
    
    {% endblock %}

    {% include 'footer.html' %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>





src/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if order.items.count > 0 %}
<div class="cart-header py-4">
    <div class="container">
        <div class="row no-gutters my-auto align-items-center">
            <div class="col-6 cart-header-left">
                <span>CART</span>
            </div>
            <div class="col-6 cart-header-right">
                <span>US${{ order.get_total }}</span>
                <a href="{% url 'core:checkout' %}"><button class="main-btn">checkout</button></a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row align-items-center">
        <div class="col">
            <div class="cart-items-list">
                <div class="cart-item">
                    {% for orderitem in order.items.all %}
                        <div class="row mt-5">
                            <div class="col-8 col-md-3 col-lg-2 mx-auto">
                                <a href="{{ orderitem.item.get_absolute_url }}">
                                    <img class="cart-item-image" src="{{ orderitem.item.image.url }}" alt="">
                                </a>
                            </div>
                            <div class="col-12 col-md-9 col-lg-10">
                                <div class="cart-info-container row mt-2">
                                    <div class="col-12 col-md-9 col-lg-7">
                                        <!-- description -->
                                        <h4 class="sub-header-text pt-2">{{ orderitem.item.title }}</h4>
                                        <ul>
                                            {% for tag in orderitem.item.description_list %}
                                                <li class="cart-description">{{ tag }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="row total-row col-12 col-lg-5 px-1">
                                        <div class="col-3 col-lg-5 px-4">
                                            <!-- quantity -->
                                            <p class="mb-0 g888">Quantity:</p>
                                            <div class="cart-quantity">
                                                <a href="{% url 'core:decrease-quantity' orderitem.item.slug %}">
                                                    <img class="chg-quantity" src="{% static 'images/qty-1.svg' %}" alt="" height="15" width="15">
                                                </a>
                                                <p class="mb-0 mx-3">{{ orderitem.quantity }}</p>
                                                <a href="{% url 'core:increase-quantity' orderitem.item.slug %}">
                                                    <img class="chg-quantity" src="{% static 'images/qty+1.svg' %}" alt="" height="15" width="15">
                                                </a>
                                            </div>
                                            <a href="{{ orderitem.item.get_remove_from_cart_url }}">
                                                <p class="text-muted mt-2 remove-link g888">Remove</p>
                                            </a>
                                        </div>
                                        <div class="flex-column col-7 col-md-4 col-lg-7 px-0">
                                            <!-- price -->
                                            <p class="cart-item-total text-end mb-0">US${{ orderitem.get_total_item_price }}</p>
                                            <p class="text-end without-discount"><del>US${{ orderitem.price_with_out_discount }}</del> {{ orderitem.item.discount_percent|floatformat }}% off</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container text-center">
    <div class="empty-cart mt-5">
        <h4>Your cart if empty</h4>
        <p class="g888">Have a look at our latest products and start shopping.</p>
        <a href="{% url 'core:home' %}"><button class="main-btn">home</button></a>
    </div>
</div>
{% endif %}
{% endblock %}

src/templates/footer.html
<footer class="text-center text-lg-start text-muted mt-5 border-top">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>GitHub code</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="https://github.com/Vuukasin/eCommerce" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company names
            </h6>
            <p>
                <a href="https://www.razer.com/" class="text-reset">Razer</a>
            </p>
            <p>
                <a href="https://steelseries.com/" class="text-reset">SteelSeries</a>
            </p>
            <p>
                <a href="https://www.logitech.com/" class="text-reset">Logitech</a>
            </p>
            <p>
                <a href="https://hyperx.com/" class="text-reset">HyperX</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="{% url 'core:gaming-laptops' %}" class="text-reset">Laptops</a>
            </p>
            <p>
              <a href="{% url 'core:gaming-mice' %}" class="text-reset">Mice</a>
            </p>
            <p>
              <a href="{% url 'core:gaming-keyboards' %}" class="text-reset">Keyboards</a>
            </p>
            <p>
              <a href="{% url 'core:gaming-audio' %}" class="text-reset">Audio</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="{% url 'core:home' %}" class="text-reset">Store</a>
            </p>
            <p>
              <a href="#" class="text-reset">Account</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              vukasinmladenovic1@gmail.com
            </p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

src/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="container mt-5">
    <!-- NEW -->
    <div class="headers mb-2">
        <h2>fresh of the line</h2>
        <div class="paragraphs">
            <p>Check out our latest releases to secure the most up-to-date upgrades for your setup</p>
            <a href="{% url 'core:new' %}"><p class="view-all">View All <span class="green">></span></p></a>
        </div>
    </div>
    <div class="grid-container">
        {% for item in new_items %}
            <div class="card-item">
                <div class="card-image-container">
                    <a href="{{ item.get_absolute_url }}">
                        <img class="card-image" src="{{ item.image.url }}" alt="">
                    </a>
                    {% if item.get_label_display %}
                    <div class="badge {{ item.get_label_display }}-badge">{{ item.get_label_display }}</div>
                    {% endif %}
               </div>
                <div class="card-body">
                    <div class="body-copy">
                        <h3>{{ item.title }}</h3>
                        <p class="summary mb-0">{{ item.summary }}</p>
                    </div>
                    <div class="cta-container">
                        <div class="price">
                            {% if item.discount %}
                                <p>US${{ item.discount }}</p>
                                <p class="text-muted mt-1"><strike>US${{ item.price }}</strike></p>
                            {% else %}
                                <p>US${{ item.price }}</p>
                            {% endif %}
                        </div>
                        <a href="{{ item.get_absolute_url }}">buy</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="banner my-5">
        <img src="{% static 'images/1202662.jpg' %}" alt="">
    </div>

    <!-- EXCLUSIVE -->
    <div class="headers mb-2 mt-5">
        <h2>exclusives</h2>
        <div class="paragraphs">
            <p>Explore unique products only available at our official online store</p>
            <a href="{% url 'core:exclusives' %}"><p class="view-all">View All <span class="green">></span></p></a>
        </div>
    </div>
    <div class="grid-container">
        {% for item in exclusive_items %}
            <div class="card-item">
                <div class="card-image-container">
                    <a href="{{ item.get_absolute_url }}">
                        <img class="card-image" src="{{ item.image.url }}" alt="">
                    </a>
                    {% if item.get_label_display %}
                    <div class="badge {{ item.get_label_display }}-badge">{{ item.get_label_display }}</div>
                    {% endif %}
               </div>
                <div class="card-body">
                    <div class="body-copy">
                        <h3>{{ item.title }}</h3>
                        <p class="summary mb-0">{{ item.summary }}</p>
                    </div>
                    <div class="cta-container">
                        <div class="price">
                            {% if item.discount %}
                                <p>US${{ item.discount }}</p>
                                <p class="text-muted mt-1"><strike>US${{ item.price }}</strike></p>
                            {% else %}
                                <p>US${{ item.price }}</p>
                            {% endif %}
                        </div>
                        <a href="{{ item.get_absolute_url }}">buy</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="banner my-5">
        <img src="{% static 'images/k-da-battle-kai-sa-league-of-legends-lol-wallpaper-2560x768_69.jpg' %}" alt="">
    </div>
    <div class="headers mb-2 mt-5">
        <h2>last chance</h2>
        <div class="paragraphs">
            <p>A curated selection of our classic gear-exclusively priced with full warranty</p>
            <a href="{% url 'core:last-chance' %}"><p class="view-all">View All <span class="green">></span></p></a>
        </div>
    </div>
    <div class="grid-container">
        {% for item in discounted_items %}
            <div class="card-item">
                <div class="card-image-container">
                    <a href="{{ item.get_absolute_url }}">
                        <img class="card-image" src="{{ item.image.url }}" alt="">
                    </a>
                    {% if item.get_label_display %}
                    <div class="badge {{ item.get_label_display }}-badge">{{ item.get_label_display }}</div>
                    {% endif %}
               </div>
                <div class="card-body">
                    <div class="body-copy">
                        <h3>{{ item.title }}</h3>
                        <p class="summary mb-0">{{ item.summary }}</p>
                    </div>
                    <div class="cta-container">
                        <div class="price">
                            {% if item.discount %}
                                <p>US${{ item.discount }}</p>
                                <p class="text-muted mt-1"><strike>US${{ item.price }}</strike></p>
                            {% else %}
                                <p>US${{ item.price }}</p>
                            {% endif %}
                        </div>
                        <a href="{{ item.get_absolute_url }}">buy</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>




{% endblock %}

src/templates/navbar.html
{% load static %}
{% load cart_template_tags %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg px-3">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler my-2"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
      <i class="fa fa-solid fa-bars"></i>
      </button>
      <a class="navbar-brand mt-lg-0" href="{% url 'core:home' %}">
        <img
          src="{% static 'images/logo.png' %}"
          height="40"
          alt="Logo"
          loading="lazy"
        />
      </a>
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:gaming-laptops' %}">Laptops</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:components' %}">Components</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:gaming-mice' %}">Mice</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:gaming-keyboards' %}">Keyboards</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:gaming-audio' %}">Audio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:streaming' %}">Streaming</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:gaming-chairs' %}">Chairs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:console-gaming' %}">Console</a>
          </li>

        </ul>
        <!-- Left links -->
      </div>


      <div class="dropdown dropstart">
          <a href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img id="cart-icon" src="{% static 'images/cart.svg' %}" alt="">
            <p id="cart-total">{{ request.user|cart_item_count }}</p>
          </a>
          <div class="dropdown-menu">
            <div class="dropdown-container text-center">
              <div class="dropdown-container-top my-3">
                <a class="my-1" href="{% url 'core:checkout' %}">
                  <button class="main-btn">checkout</button>
                </a>
              </div>
              <ul class="text-start">
                <li>
                  <a href="{% url 'core:cart' %}">
                    <img src="{% static 'images/cart.svg' %}" alt="" height="26">
                    Cart({{ request.user|cart_item_count }})
                  </a>
                </li>
                <li>
                  <a href="{% url 'core:orders' %}">
                    <img src="{% static 'images/orders.svg' %}" alt="" height="26">
                    Orders
                  </a>
                </li>
                {% if request.user.is_authenticated %}
                <li>
                  <a href="{% url 'account_logout' %}">
                    <img src="{% static 'images/logout.svg' %}" alt="" height="26">
                    Logout
                  </a>
                </li>
                {% else %}
                <li>
                  <a href="{% url 'account_login' %}">
                    <img src="{% static 'images/logout.svg' %}" alt="" height="26">
                    Login
                  </a>
                </li>
                <li>
                  <a href="{% url 'account_signup' %}">
                    <img src="{% static 'images/logout.svg' %}" alt="" height="26">
                    Signup
                  </a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
      </div>
    </div>
  </nav>

src/templates/orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">

    <h2 class="orders-header">Order History</h2>
    <table>
        <thead>
          <tr>
            <th>Order Code</th>
            <th>Order Date</th>
            <th>Creation Date</th>
            <th>Status</th>
            <th>Order Amount</th>
          </tr>
         </thead>
         <tbody>
            {% for order in orders %}
            <tr>
                <td class="green">{{ order.ref_code }}</td>
                <td>{{ order.ordered_date|date:"d/m/Y" }}</td>
                <td>{{ order.created|date:"d/m/Y" }}</td>
                <td>{{ order.get_status_display }}</td>
                <td>US${{ order.get_total }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      

</div>
{% endblock %}

src/templates/product_added.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container product-added">

    <div class="row my-5 align-items-center">
        <div class="col-lg-2 col-0">
            <img class="product-added-image" src="{{ item.image.url }}" alt="">
        </div>
        <div class="col-lg-8">
            <h3>{{ item.title }} has been added</h3>
            {% for tag in item.description_list %}
            <div class="product-added-description">
                {% if tag %}
                <li>{{ tag }}</li>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <div class="col-lg-2">
            <a href="{% url 'core:cart' %}">
                <button class="main-btn">view cart</button>
            </a>
        </div>
    </div>

</div>

{% endblock %}